name: Automation

on:
    workflow_dispatch:
    schedule:
        - cron: "0/5 * * * *"

env:
    GH_TOKEN: ${{ github.token }}

jobs:
    automated-workflow-run:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger backup workflow
              run: |
                  gh workflow run orchestration.yml
